export const MAJOR_PARTS = [
  {
    id: "cyl-1",
    name: "Cylinder 1",
    mat: "Dark Graphite & Silver Head",
    cat: "Combustion Chamber",
    pos: [0.24, 0.05, -0.12],
    desc: "Aft right horizontally opposed combustion cylinder with forged alloy piston.",
  },
  {
    id: "cyl-2",
    name: "Cylinder 2",
    mat: "Dark Graphite & Silver Head",
    cat: "Combustion Chamber",
    pos: [-0.24, 0.05, -0.04],
    desc: "Aft left cylinder assembly. Monitored for ignition and oil telemetry anomalies.",
  },
  {
    id: "cyl-3",
    name: "Cylinder 3",
    mat: "Dark Graphite & Silver Head",
    cat: "Combustion Chamber",
    pos: [0.24, 0.05, 0.04],
    desc: "Forward right cylinder with dual spark ignition and high thermal conductivity.",
  },
  {
    id: "cyl-4",
    name: "Cylinder 4",
    mat: "Dark Graphite & Silver Head",
    cat: "Combustion Chamber",
    pos: [-0.24, 0.05, 0.12],
    desc: "Forward left horizontally opposed cylinder with tuned exhaust scavenging.",
  },
  {
    id: "heads",
    name: "Cylinder Head",
    mat: "Silver Aluminium",
    cat: "Top End / Valvetrain",
    pos: [0.25, 0.08, -0.12],
    desc: "CNC silver aluminium heads with multi-angle valve seats and dual spark bosses.",
  },
  {
    id: "fins",
    name: "Cooling Fins",
    mat: "Black Graphite",
    cat: "Thermal Dissipation",
    pos: [0.15, 0.0, 0.04],
    desc: "High-density aerodynamic black graphite fins for forced convection cooling.",
  },
  {
    id: "crankcase",
    name: "Crankcase",
    mat: "Brushed Aluminium",
    cat: "Structural Core",
    pos: [0, 0.02, 0],
    desc: "Split-case brushed aerospace aluminium housing supporting crankshaft main journals.",
  },
  {
    id: "manifold",
    name: "Intake System",
    mat: "Metallic Grey",
    cat: "Air Delivery",
    pos: [0, 0.14, -0.05],
    desc: "Balanced intake plenum with tuned velocity stacks and throttle body control.",
  },
  {
    id: "exhaust",
    name: "Exhaust System",
    mat: "Dark Bronze / Copper",
    cat: "Scavenging",
    pos: [0, -0.17, -0.35],
    desc: "Heat-resistant dark bronze alloy manifold and tuned acoustic muffler.",
  },
  {
    id: "oil",
    name: "Oil System",
    mat: "Dark Metallic",
    cat: "Lubrication",
    pos: [0.08, -0.08, -0.22],
    desc: "Dry-sump pressure pump, high-capacity filter, and scavenge return galleries.",
  },
  {
    id: "fuel",
    name: "Fuel System",
    mat: "Dark Grey/Blue",
    cat: "Fuel Metering",
    pos: [0.12, 0.17, -0.15],
    desc: "High-pressure common fuel rails, injectors, and electronic pressure regulator.",
  },
  {
    id: "ecu",
    name: "ECU & Wiring",
    mat: "Dark Charcoal",
    cat: "Avionics / FADEC",
    pos: [-0.09, 0.04, -0.25],
    desc: "Dual-redundant Full Authority Digital Engine Controller and shielded harness.",
  },
  {
    id: "gearbox",
    name: "Gearbox",
    mat: "Gunmetal Alloy",
    cat: "Speed Reduction",
    pos: [0, 0.02, 0.22],
    desc: "Precision spur gear reduction drive with integrated torsional vibration damper.",
  },
  {
    id: "shaft",
    name: "Output Shaft",
    mat: "High-Tensile Steel",
    cat: "Drivetrain",
    pos: [0, 0, 0.27],
    desc: "Hardened output prop shaft rated for high gyroscopic and aerodynamic loads.",
  },
  {
    id: "propeller",
    name: "Propeller",
    mat: "Carbon-Fibre Black",
    cat: "Thrust Unit",
    pos: [0, 0.35, 0.34],
    desc: "3-blade high-efficiency scimitar composite propeller with carbon-fibre weave.",
  },
] as const;

export type EnginePartId = (typeof MAJOR_PARTS)[number]["id"];
